# Generated by Django 4.2.1 on 2023-05-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_image_product_img_alter_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="img",
            new_name="imagens",
        ),
    ]
