# Generated by Django 4.2.1 on 2023-06-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
