# Generated by Django 4.2.1 on 2023-07-27 14:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=django_mysql.models.ListCharField(
                models.CharField(max_length=10), default=["M"], max_length=66, size=6
            ),
        ),
    ]
