# Generated by Django 4.2.1 on 2023-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="slug_padrao"),
        ),
    ]
