# Generated by Django 4.2.1 on 2023-07-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_size_remove_product_size_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="name",
            field=models.CharField(default="P", max_length=1),
        ),
    ]
