# Generated by Django 4.2.1 on 2023-07-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_size_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="size",
            name="name",
        ),
    ]
