# Generated by Django 4.2.1 on 2023-06-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("app", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=128)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("created", "Criado"),
                            ("paid", "Pago"),
                            ("shipped", "Enviado"),
                            ("refunded", "Devolvido"),
                        ],
                        default="created",
                        max_length=64,
                    ),
                ),
                (
                    "preco_prazo",
                    models.DecimalField(decimal_places=2, default=10.99, max_digits=64),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=64),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.address",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cart.carrinho",
                    ),
                ),
            ],
        ),
    ]
