# Generated by Django 4.2.4 on 2023-11-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidos",
            name="preco_prazo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
    ]
